### ISSUE TITLE
Null Index

### ISSUE THREAD

**Issue by Tarious60** [BrianOstrander/pz-save-our-station#5]
`attempted index: stages of non-table: null
function: FillBroadcastWarning -- file: SWWS_Core.lua line # 389 | MOD: Save Our Station - Core
function: FillBroadcast -- file: SWWS_ISWeatherChannelOverride.lua line # 8 | MOD: Save Our Station - Core
function: CreateBroadcast -- file: ISWeatherChannel.lua line # 114 | Vanilla
function: OnEveryHour -- file: ISWeatherChannel.lua line # 100 | Vanilla
function: OnEveryHour -- file: ISDynamicRadio.lua line # 154 | Vanilla
java.lang.RuntimeException: attempted index: stages of non-table: null
    at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
    at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
    at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
    at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
    at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
    at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
    at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
    at zombie.Lua.Event.trigger(Event.java:64)
    at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
    at zombie.GameTime.update(GameTime.java:550)
    at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
    at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
    at zombie.gameStates.IngameState.update(IngameState.java:1333)
    at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
    at zombie.GameWindow.logic(GameWindow.java:298)
    at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
    at zombie.GameWindow.frameStep(GameWindow.java:765)
    at zombie.GameWindow.run_ez(GameWindow.java:681)
    at zombie.GameWindow.mainThread(GameWindow.java:495)
    at java.base/java.lang.Thread.run(Unknown Source)
`

Broadcasts trigger the first time a new game is loaded, but after that, an exception is thrown every hour on the hour and no dialogue comes from the radio at all besides the default <Wzzrt.> disconnected noises. I have been able to replicate this on clean installs, without mods, and only Save our Station.

**Comment by YoshiWoof22** [comment]
@Tarious60 - Thank you for the report ^^

I just fired up a new world with just SOS Core and SOS Knox Country enabled to see if I'm able to reproduce this on my end, but I've thus far not been able to replicate your issue.

For whatever reason, it looks like Save Our Station isn't initializing correctly on your end. I'm unsure as to why that would be happening...

Are you able to zip up and attach an affected Save File (usually located in `C:\Users\<YOUR_USERNAME>\Zomboid\Saves`) along with the Log Files so we can check it out on our end? In addition, try validating your files, to make sure no mod data is potentially corrupted.

Thanks in advance!

**Comment by Tarious60** [comment]
Thank you for your swift reply!

After a few more clean tests and validations, the culprit was definitely some missing or corrupt mod data in the SOS Knox Country (sub?)mod, I don't think it was firing at all. I'm now able to hear the broadcast more than the first time and I don't get Lua Exceptions anymore every hour on the hour.

Sorry this ended up being so anticlimactic, but you definitely diagnosed it right off the bat; thanks a bunch.
